name: "✨ Website Feature Request"
description: "Suggest a new idea or improvement for the website"
title: "[Website Feature]: "
labels: ["enhancement", "website"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a website improvement! Please fill out the details below so we can review it 🧠

  - type: input
    id: page
    attributes:
      label: "🌍 Related Page / Section"
      description: "Which page or section would this feature affect?"
      placeholder: "bluecube.pages.dev/cool"
    validations:
      required: true

  - type: input
    id: summary
    attributes:
      label: "💡 Feature Summary"
      description: "Briefly describe the feature you want."
      placeholder: "Add a dark mode toggle"
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: "🔥 Why is this needed?"
      description: "Explain why this feature would help users."
      placeholder: "Many users prefer dark mode for nighttime browsing."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: "🧠 Suggested Implementation"
      description: "Optional ideas on how to implement it."
      placeholder: "Could add a switch in the header that toggles a dark theme class."
    validations:
      required: false

  - type: textarea
    id: extra
    attributes:
      label: "📎 Additional Context"
      description: "Screenshots, sketches, or other details."
      placeholder: "Attach wireframes, examples, or links here."
    validations:
      required: false
